package com.rafael.labmanager

import android.app.AlertDialog
import android.content.Context
import android.graphics.Color
import android.graphics.Typeface
import android.os.Bundle
import android.view.Gravity
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import com.google.android.material.button.MaterialButton
import com.google.android.material.card.MaterialCardView
import com.google.android.material.textfield.TextInputEditText
import com.google.android.material.textfield.TextInputLayout
import org.json.JSONArray
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.*

/** Integrated LIS workflow for LabManager. Local persistence is used in this MVP. */
class LisActivity : AppCompatActivity() {
    private val db by lazy { getSharedPreferences("labmanager_lis_v2", Context.MODE_PRIVATE) }
    private lateinit var root: LinearLayout
    private val navy=Color.rgb(18,45,72); private val blue=Color.rgb(28,112,184); private val orange=Color.rgb(239,125,45)
    private val green=Color.rgb(48,133,87); private val red=Color.rgb(190,65,65); private val bg=Color.rgb(246,248,251)
    private val text=Color.rgb(31,43,56); private val muted=Color.rgb(100,114,130)
    private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
    private fun now()=SimpleDateFormat("dd/MM/yyyy HH:mm",Locale("pt","BR")).format(Date())
    private fun uid()=UUID.randomUUID().toString().substring(0,8).uppercase()
    private fun list(k:String):MutableList<JSONObject>{val a=JSONArray(db.getString(k,"[]"));return MutableList(a.length()){a.getJSONObject(it)}}
    private fun save(k:String,l:List<JSONObject>){val a=JSONArray();l.forEach{a.put(it)};db.edit().putString(k,a.toString()).apply()}
    private fun add(k:String,o:JSONObject){val l=list(k);l.add(o);save(k,l);event("$k • ${o.optString("id")}")}
    private fun event(s:String){val l=list("audit");l.add(JSONObject().apply{put("id",uid());put("event",s);put("date",now())});save("audit",l)}
    private fun tv(s:String,z:Float,c:Int,b:Boolean=false)=TextView(this).apply{text=s;textSize=z;setTextColor(c);if(b)setTypeface(null,Typeface.BOLD)}
    override fun onCreate(b:Bundle?){super.onCreate(b);home()}
    private fun page(title:String,sub:String=""){root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(18),dp(16),dp(18),dp(28));setBackgroundColor(bg)};val sc=ScrollView(this).apply{setBackgroundColor(bg);addView(root)};root.addView(tv(title,27f,navy,true));if(sub.isNotBlank())root.addView(tv(sub,13f,muted).apply{setPadding(0,dp(4),0,dp(10))});setContentView(sc)}
    private fun button(s:String,c:Int=blue,f:()->Unit){val b=MaterialButton(this).apply{text=s;isAllCaps=false;textSize=14f;setTextColor(Color.WHITE);backgroundTintList=android.content.res.ColorStateList.valueOf(c);cornerRadius=dp(11);minimumHeight=dp(50);setOnClickListener{f()}};root.addView(b,LinearLayout.LayoutParams(-1,dp(52)).apply{setMargins(0,dp(5),0,dp(5))})}
    private fun secondary(s:String,f:()->Unit){val b=MaterialButton(this).apply{text=s;isAllCaps=false;textSize=13f;setTextColor(navy);backgroundTintList=android.content.res.ColorStateList.valueOf(Color.WHITE);strokeWidth=dp(1);strokeColor=android.content.res.ColorStateList.valueOf(Color.rgb(205,214,224));cornerRadius=dp(11);setOnClickListener{f()}};root.addView(b,LinearLayout.LayoutParams(-1,dp(48)).apply{setMargins(0,dp(4),0,dp(4))})}
    private fun section(s:String){root.addView(tv(s,18f,navy,true).apply{setPadding(dp(2),dp(17),0,dp(6))})}
    private fun field(h:String,v:String="",multi:Boolean=false):EditText{val t=TextInputLayout(this).apply{hint=h;boxBackgroundMode=TextInputLayout.BOX_BACKGROUND_OUTLINE};t.shapeAppearanceModel=t.shapeAppearanceModel.toBuilder().setAllCornerSizes(dp(10).toFloat()).build();val e=TextInputEditText(this).apply{setText(v);textSize=15f;if(multi)minLines=3};t.addView(e);root.addView(t,LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,dp(4),0,dp(4))});return e}
    private fun card(title:String,body:String,color:Int=blue,action:(()->Unit)?=null){val c=MaterialCardView(this).apply{radius=dp(14).toFloat();cardElevation=dp(2).toFloat();setCardBackgroundColor(Color.WHITE);setContentPadding(dp(15),dp(13),dp(15),dp(13));if(action!=null){isClickable=true;setOnClickListener{action()}}};val x=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};x.addView(tv(title,15f,text,true));x.addView(tv(body,12.5f,muted).apply{setPadding(0,dp(5),0,0)});c.addView(x);root.addView(c,LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,dp(4),0,dp(4))})}
    private fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_SHORT).show()

    private fun home(){page("LabManager","LIS • gestão laboratorial ponta a ponta");section("Painel operacional");card("Atendimento","${list("patients").size} pacientes cadastrados");card("Pedidos","${list("orders").count{it.optString("status")!="Liberada"}} pedidos em fluxo",orange);card("Amostras","${list("samples").count{it.optString("status")!="Liberada"&&it.optString("status")!="Rejeitada"}} em processamento",blue);card("Resultados","${list("results").count{it.optString("status")!="Liberado"}} aguardando liberação",green);card("Estoque crítico","${list("stock").count{it.optInt("qty")<=it.optInt("min")}} itens",red);section("Operação");button("Atendimento • Pacientes"){patients()};button("Pedidos • Convênios • Exames"){orders()};button("Coleta • Triagem • Recoleta"){samples()};button("Área técnica • Resultados • Liberação"){technical()};button("Estoque • Lotes • Validade"){stock()};button("Qualidade • CIQ • Não conformidades"){quality()};button("Faturamento • Financeiro"){finance()};button("BI • Auditoria • Rastreabilidade"){reports()};secondary("Sair do LIS"){finish()}}

    private fun patients(){page("Atendimento","Cadastro, busca e histórico");button("Novo paciente"){patientForm()};section("Pacientes");list("patients").forEach{p->card(p.optString("name"),"${p.optString("id")} • ${p.optString("phone","-")}\n${p.optString("insurance","Particular")}"){patient(p.optString("id"))}};if(list("patients").isEmpty())root.addView(tv("Nenhum paciente.",14f,muted));secondary("Voltar"){home()}}
    private fun patientForm(existing:JSONObject?=null){page(if(existing==null)"Novo paciente" else "Editar paciente","Dados cadastrais");val n=field("Nome completo",existing?.optString("name","")?:"");val ph=field("Telefone / WhatsApp",existing?.optString("phone","")?:"");val birth=field("Data de nascimento",existing?.optString("birth","")?:"");val cpf=field("CPF",existing?.optString("cpf","")?:"");val sex=field("Sexo",existing?.optString("sex","")?:"");val addr=field("Endereço",existing?.optString("address","")?:"");val ins=field("Convênio",existing?.optString("insurance","Particular")?:"Particular");val obs=field("Observações",existing?.optString("obs","")?:"",true);button("Salvar paciente"){if(n.text.toString().isBlank()){toast("Nome obrigatório");return@button};val l=list("patients");val p=existing?:JSONObject().apply{put("id","PAT-${uid()}");put("created",now())};p.put("name",n.text.toString().trim());p.put("phone",ph.text.toString());p.put("birth",birth.text.toString());p.put("cpf",cpf.text.toString());p.put("sex",sex.text.toString());p.put("address",addr.text.toString());p.put("insurance",ins.text.toString());p.put("obs",obs.text.toString());p.put("updated",now());if(existing==null)l.add(p);save("patients",l);event("Paciente ${p.optString("id")} atualizado");patients()};secondary("Cancelar"){patients()}}
    private fun patient(id:String){val p=list("patients").firstOrNull{it.optString("id")==id}?:return;page("Ficha do paciente","Histórico integrado");card(p.optString("name"),"${p.optString("birth","-")} • ${p.optString("sex","-")}\n${p.optString("phone","-")} • ${p.optString("insurance","Particular")}");section("Pedidos");list("orders").filter{it.optString("patientId")==id}.forEach{o->card(o.optString("exam"),"${o.optString("id")} • ${o.optString("status")}")};section("Resultados");list("results").filter{it.optString("patientId")==id}.forEach{r->card(r.optString("exam"),"${r.optString("value")} ${r.optString("unit")} • ${r.optString("status")}")};button("Novo pedido"){orderForm(id)};secondary("Editar"){patientForm(p)};secondary("Voltar"){patients()}}

    private fun orders(){page("Pedidos e exames","Requisição, convênio e fluxo laboratorial");button("Nova requisição"){orderForm()};section("Pedidos");list("orders").forEach{o->card("${o.optString("id")} • ${o.optString("exam")}","Paciente: ${o.optString("patient")}\nMaterial: ${o.optString("material")} • ${o.optString("insurance")}\nStatus: ${o.optString("status")}");secondary("Avançar etapa"){advanceOrder(o.optString("id"));orders()}};secondary("Voltar"){home()}}
    private fun orderForm(patientId:String?=null){page("Nova requisição","Pedido de exames");val pn=patientId?.let{id->list("patients").firstOrNull{it.optString("id")==id}?.optString("name","")}?:"";val patient=field("Paciente",pn);val exam=field("Exame solicitado");val material=field("Material biológico");val priority=field("Prioridade","Rotina");val physician=field("Médico solicitante");val insurance=field("Convênio / particular","Particular");val notes=field("Observações","",true);button("Gerar pedido"){if(patient.text.toString().isBlank()||exam.text.toString().isBlank()){toast("Paciente e exame obrigatórios");return@button};val p=list("patients").firstOrNull{it.optString("name").equals(patient.text.toString().trim(),true)};add("orders",JSONObject().apply{put("id","REQ-${uid()}");put("patientId",p?.optString("id",patientId?:"")?:(patientId?:""));put("patient",patient.text.toString());put("exam",exam.text.toString());put("material",material.text.toString());put("priority",priority.text.toString());put("physician",physician.text.toString());put("insurance",insurance.text.toString());put("notes",notes.text.toString());put("status","Solicitada");put("created",now())});toast("Pedido criado");orders()};secondary("Cancelar"){orders()}}
    private fun advanceOrder(id:String){val st=listOf("Solicitada","Recebida","Em processamento","Resultado","Liberada");val l=list("orders");l.firstOrNull{it.optString("id")==id}?.let{o->{val i=st.indexOf(o.optString("status"));o.put("status",st[minOf(i+1,st.lastIndex)]);o.put("updated",now())}};save("orders",l);event("Pedido $id avançou")}

    private fun samples(){page("Coleta e triagem","Identificação, recebimento, aceitação e recoleta");button("Registrar coleta"){sampleForm()};section("Amostras");list("samples").forEach{s->card("${s.optString("barcode")} • ${s.optString("material")}","Paciente: ${s.optString("patient")}\n${s.optString("status")} • ${s.optString("collectedAt")}",if(s.optString("status")=="Rejeitada")red else blue);secondary("Avançar etapa"){advanceSample(s.optString("id"));samples()};if(s.optString("status")=="Triagem")secondary("Rejeitar / recoleta"){rejectSample(s.optString("id"));samples()}};secondary("Voltar"){home()}}
    private fun sampleForm(){page("Registrar coleta","Rastreabilidade da amostra");val barcode=field("Código de barras","LAB-${uid()}");val patient=field("Paciente");val material=field("Material / tubo");val collector=field("Coletador");val origin=field("Posto / origem");val condition=field("Condição","Adequada");button("Registrar amostra"){if(patient.text.toString().isBlank()||material.text.toString().isBlank()){toast("Paciente e material obrigatórios");return@button};val p=list("patients").firstOrNull{it.optString("name").equals(patient.text.toString().trim(),true)};add("samples",JSONObject().apply{put("id","SMP-${uid()}");put("barcode",barcode.text.toString());put("patientId",p?.optString("id","")?:"");put("patient",patient.text.toString());put("material",material.text.toString());put("collector",collector.text.toString());put("origin",origin.text.toString());put("condition",condition.text.toString());put("status","Coletada");put("collectedAt",now());put("updated",now())});samples()};secondary("Cancelar"){samples()}}
    private fun advanceSample(id:String){val st=listOf("Coletada","Recebida","Triagem","Em processamento","Resultado","Liberada");val l=list("samples");l.firstOrNull{it.optString("id")==id}?.let{s->{val i=st.indexOf(s.optString("status"));s.put("status",st[minOf(i+1,st.lastIndex)]);s.put("updated",now())}};save("samples",l);event("Amostra $id avançou")}
    private fun rejectSample(id:String){val l=list("samples");l.firstOrNull{it.optString("id")==id}?.let{it.put("status","Rejeitada");it.put("recollection",true);it.put("updated",now())};save("samples",l);event("Amostra $id rejeitada / recoleta")}

    private fun technical(){page("Área técnica","Lista de trabalho • digitação • conferência • liberação");button("Digitar resultado"){resultForm()};button("Liberar todos os resultados conferidos",green){list("results").filter{it.optString("status")=="Conferido"}.forEach{releaseResult(it.optString("id"))};technical()};section("Resultados");list("results").forEach{r->card("${r.optString("exam")} • ${r.optString("patient")}","Resultado: ${r.optString("value")} ${r.optString("unit")}\nReferência: ${r.optString("reference")}\nStatus: ${r.optString("status")}\nResponsável: ${r.optString("professional")}",if(r.optString("status")=="Liberado")green else orange);if(r.optString("status")!="Liberado")secondary("Conferir") {val l=list("results");l.firstOrNull{it.optString("id")==r.optString("id")}?.put("status","Conferido");save("results",l);event("Resultado ${r.optString("id")} conferido");technical()}};section("Pedidos em processamento");list("orders").filter{it.optString("status")=="Em processamento"}.forEach{o->card(o.optString("id"),"${o.optString("patient")} • ${o.optString("exam")}"){resultForm(o)}};secondary("Voltar"){home()}}
    private fun resultForm(order:JSONObject?=null){page("Resultado","Digitação técnica e valores de referência");val p=field("Paciente",order?.optString("patient","")?:"");val e=field("Exame",order?.optString("exam","")?:"");val v=field("Resultado");val u=field("Unidade");val ref=field("Referência");val method=field("Método");val prof=field("Responsável técnico");val critical=field("Resultado crítico?","Não");val comment=field("Comentário","",true);button("Salvar resultado"){if(p.text.toString().isBlank()||e.text.toString().isBlank()||v.text.toString().isBlank()){toast("Paciente, exame e resultado obrigatórios");return@button};val patientObj=list("patients").firstOrNull{it.optString("name").equals(p.text.toString().trim(),true)};add("results",JSONObject().apply{put("id","RES-${uid()}");put("orderId",order?.optString("id","")?:"");put("patientId",patientObj?.optString("id","")?:order?.optString("patientId","")?:(""));put("patient",p.text.toString());put("exam",e.text.toString());put("value",v.text.toString());put("unit",u.text.toString());put("reference",ref.text.toString());put("method",method.text.toString());put("professional",prof.text.toString());put("critical",critical.text.toString());put("comment",comment.text.toString());put("status","Digitado");put("created",now())});if(order!=null){val l=list("orders");l.firstOrNull{it.optString("id")==order.optString("id")}?.put("status","Resultado");save("orders",l)};technical()};secondary("Cancelar"){technical()}}
    private fun releaseResult(id:String){val l=list("results");l.firstOrNull{it.optString("id")==id}?.let{it.put("status","Liberado");it.put("releasedAt",now())};save("results",l);event("Resultado $id liberado")}

    private fun stock(){page("Estoque","Insumos, reagentes, lotes, validade e consumo");button("Novo item"){stockForm()};section("Itens");list("stock").forEach{s->val critical=s.optInt("qty")<=s.optInt("min");card("${s.optString("name")} • Lote ${s.optString("lot")}","${s.optInt("qty")} ${s.optString("unit")} • mínimo ${s.optInt("min")}\nValidade: ${s.optString("expiry")} • Fornecedor: ${s.optString("supplier","-")}",if(critical)red else green);secondary("Consumir 1 unidade"){val l=list("stock");l.firstOrNull{it.optString("id")==s.optString("id")}?.let{it.put("qty",maxOf(0,it.optInt("qty")-1));it.put("updated",now())};save("stock",l);event("Consumo de estoque ${s.optString("id")}");stock()}};secondary("Voltar"){home()}}
    private fun stockForm(){page("Novo insumo","Controle de lote e validade");val n=field("Nome");val lot=field("Lote");val exp=field("Validade");val q=field("Quantidade","0");val min=field("Estoque mínimo","0");val unit=field("Unidade","un");val sup=field("Fornecedor");button("Salvar item"){add("stock",JSONObject().apply{put("id","STK-${uid()}");put("name",n.text.toString());put("lot",lot.text.toString());put("expiry",exp.text.toString());put("qty",q.text.toString().toIntOrNull()?:0);put("min",min.text.toString().toIntOrNull()?:0);put("unit",unit.text.toString());put("supplier",sup.text.toString());put("created",now())});stock()};secondary("Cancelar"){stock()}}

    private fun quality(){page("Qualidade","CIQ, ocorrências, não conformidades e ações");button("Registrar não conformidade"){ncForm()};button("Registrar CIQ"){qcForm()};section("Não conformidades");list("ncs").forEach{n->card("${n.optString("id")} • ${n.optString("category")}","${n.optString("description")}\n${n.optString("status")} • ${n.optString("owner")}",if(n.optString("status")=="Concluída")green else orange);if(n.optString("status")!="Concluída")secondary("Concluir ação"){val l=list("ncs");l.firstOrNull{it.optString("id")==n.optString("id")}?.put("status","Concluída");save("ncs",l);event("NC ${n.optString("id")} concluída");quality()}};section("CIQ");list("qc").forEach{q->card("${q.optString("analyte")} • ${q.optString("level")}","Resultado: ${q.optString("value")} • Média: ${q.optString("mean")} • DP: ${q.optString("sd")}\nInterpretação: ${q.optString("rule")}\n${q.optString("date")}")};secondary("Voltar"){home()}}
    private fun ncForm(){page("Não conformidade");val c=field("Categoria","Amostra");val d=field("Descrição","",true);val o=field("Responsável");val a=field("Ação corretiva / plano de ação","",true);button("Registrar"){add("ncs",JSONObject().apply{put("id","NC-${uid()}");put("category",c.text.toString());put("description",d.text.toString());put("owner",o.text.toString());put("action",a.text.toString());put("status","Aberta");put("created",now())});quality()};secondary("Cancelar"){quality()}}
    private fun qcForm(){page("Controle interno da qualidade");val a=field("Analito");val l=field("Nível","Controle 1");val v=field("Resultado");val m=field("Média");val sd=field("Desvio padrão");val r=field("Interpretação / regra","Dentro do controle");button("Registrar CIQ"){add("qc",JSONObject().apply{put("id","QC-${uid()}");put("analyte",a.text.toString());put("level",l.text.toString());put("value",v.text.toString());put("mean",m.text.toString());put("sd",sd.text.toString());put("rule",r.text.toString());put("date",now())});quality()};secondary("Cancelar"){quality()}}

    private fun finance(){page("Faturamento e financeiro","Receitas, despesas, convênios e pendências");button("Novo lançamento"){financeForm()};val l=list("finance");val rec=l.filter{it.optString("type")=="Receita"}.sumOf{it.optDouble("amount")};val desp=l.filter{it.optString("type")=="Despesa"}.sumOf{it.optDouble("amount")};section("Resumo");card("Receitas","R$ %.2f".format(Locale("pt","BR"),rec),green);card("Despesas","R$ %.2f".format(Locale("pt","BR"),desp),red);card("Saldo","R$ %.2f".format(Locale("pt","BR"),rec-desp),blue);section("Lançamentos");l.forEach{f->card(f.optString("description"),"${f.optString("type")} • R$ ${f.optString("amount")} • ${f.optString("date")}\n${f.optString("payer")}")};secondary("Voltar"){home()}}
    private fun financeForm(){page("Novo lançamento");val type=field("Tipo","Receita");val d=field("Descrição");val amount=field("Valor","0");val payer=field("Convênio / cliente");val center=field("Centro de custo");button("Salvar"){add("finance",JSONObject().apply{put("id","FIN-${uid()}");put("type",type.text.toString());put("description",d.text.toString());put("amount",amount.text.toString().replace(",",".").toDoubleOrNull()?:0.0);put("payer",payer.text.toString());put("costCenter",center.text.toString());put("date",now())});finance()};secondary("Cancelar"){finance()}}

    private fun reports(){page("BI, auditoria e rastreabilidade","Indicadores operacionais e trilha de eventos");section("Indicadores");card("Pacientes",list("patients").size.toString());card("Pedidos",list("orders").size.toString());card("Amostras",list("samples").size.toString());card("Resultados",list("results").size.toString());card("Liberados",list("results").count{it.optString("status")=="Liberado"}.toString(),green);card("NC abertas",list("ncs").count{it.optString("status")!="Concluída"}.toString(),orange);card("Estoque crítico",list("stock").count{it.optInt("qty")<=it.optInt("min")}.toString(),red);section("Auditoria / rastreabilidade");list("audit").takeLast(30).reversed().forEach{a->card(a.optString("date"),a.optString("event"))};secondary("Voltar"){home()}}
}
