package com.rafael.labmanager

import android.app.AlertDialog
import android.content.Context
import android.os.Bundle
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import org.json.JSONArray
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.*

class MainActivity:AppCompatActivity(){
 private val db by lazy{getSharedPreferences("labmanager_db",Context.MODE_PRIVATE)}
 private lateinit var root:LinearLayout
 private fun data(k:String):MutableList<JSONObject>{val a=JSONArray(db.getString(k,"[]"));return MutableList(a.length()){a.getJSONObject(it)}}
 private fun save(k:String,l:List<JSONObject>){val a=JSONArray();l.forEach{a.put(it)};db.edit().putString(k,a.toString()).apply()}
 private fun id()=UUID.randomUUID().toString()
 private fun now()=SimpleDateFormat("dd/MM/yyyy HH:mm",Locale("pt","BR")).format(Date())
 override fun onCreate(b:Bundle?){super.onCreate(b);home()}
 private fun page(t:String){root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(24,24,24,24)};root.addView(TextView(this).apply{text=t;textSize=28f});setContentView(ScrollView(this).apply{addView(root)})}
 private fun button(t:String,f:()->Unit){root.addView(Button(this).apply{text=t;setOnClickListener{f()}})}
 private fun label(t:String){root.addView(TextView(this).apply{text=t;textSize=16f;setPadding(4,10,4,10)})}
 private fun field(h:String,v:String="")=EditText(this).apply{hint=h;setText(v)}
 private fun home(){page("LabManager");label("Sistema de gestão laboratorial");label("Pacientes: ${data("patients").size}   Solicitações: ${data("requests").size}   Amostras: ${data("samples").size}   Estoque: ${data("stock").size}");button("👤 Pacientes"){patients()};button("🧾 Solicitações de exames"){requests()};button("🔬 Amostras"){samples()};button("📦 Estoque e validade"){stock()};button("📊 Resultados e relatórios"){reports()};button("📅 Agendamentos"){appointments()};button("🩺 Consultas"){consultations()}}
 private fun patients(){page("Pacientes");button("+ Novo cadastro"){patientForm(null)};val l=data("patients");if(l.isEmpty())label("Nenhum paciente cadastrado.");l.forEach{p->label("${p.optString("name")}\n${p.optString("phone")} • ${p.optString("birth")}");button("Visualizar"){details(p)};button("Editar"){patientForm(p)};button("Excluir"){delete("patients",p.optString("id")){patients()}}};button("← Voltar"){home()}}
 private fun patientForm(old:JSONObject?){page(if(old==null)"Novo paciente" else "Editar paciente");val n=field("Nome completo",old?.optString("name")?:(""));val ph=field("Telefone",old?.optString("phone")?:(""));val b=field("Data de nascimento",old?.optString("birth")?:(""));val cpf=field("CPF (opcional)",old?.optString("cpf")?:(""));val addr=field("Endereço",old?.optString("address")?:(""));val notes=field("Observações",old?.optString("notes")?:(""));listOf(n,ph,b,cpf,addr,notes).forEach{root.addView(it)};button("Salvar"){if(n.text.isBlank()||ph.text.isBlank()||b.text.isBlank()){toast("Preencha nome, telefone e nascimento");return@button};val p=old?:JSONObject().put("id",id());p.put("name",n.text.toString()).put("phone",ph.text.toString()).put("birth",b.text.toString()).put("cpf",cpf.text.toString()).put("address",addr.text.toString()).put("notes",notes.text.toString());val l=data("patients");l.removeAll{it.optString("id")==p.optString("id")};l.add(p);save("patients",l);patients()};button("Cancelar"){patients()}}
 private fun details(p:JSONObject){page("Ficha do paciente");label("Nome: ${p.optString("name")}\nTelefone: ${p.optString("phone")}\nNascimento: ${p.optString("birth")}\nCPF: ${p.optString("cpf").ifBlank{"—"}}\nEndereço: ${p.optString("address").ifBlank{"—"}}\nObservações: ${p.optString("notes").ifBlank{"—"}}");label("Solicitações: ${data("requests").count{it.optString("patientId")==p.optString("id")}} | Amostras: ${data("samples").count{it.optString("patientId")==p.optString("id")}}");button("← Voltar"){patients()}}
 private fun requests(){page("Solicitações de exames");button("+ Nova solicitação"){requestForm()};val l=data("requests");if(l.isEmpty())label("Nenhuma solicitação.");l.forEach{r->label("${r.optString("patientName")}\n${r.optString("exams")}\n${r.optString("date")} • ${r.optString("status")}");button("Avançar status"){val s=listOf("Solicitada","Recebida","Em processamento","Resultado","Liberada");r.put("status",s[(s.indexOf(r.optString("status"))+1).coerceAtMost(4)]);save("requests",l);requests()}};button("← Voltar"){home()}}
 private fun requestForm(){val ps=data("patients");if(ps.isEmpty()){toast("Cadastre um paciente primeiro");return};page("Nova solicitação");val sp=Spinner(this).apply{adapter=ArrayAdapter(this@MainActivity,android.R.layout.simple_spinner_dropdown_item,ps.map{it.optString("name")})};root.addView(sp);val e=field("Exames (Hemograma, Glicemia...)");val o=field("Observações");root.addView(e);root.addView(o);button("Salvar"){val p=ps[sp.selectedItemPosition];val r=JSONObject().put("id",id()).put("patientId",p.optString("id")).put("patientName",p.optString("name")).put("exams",e.text.toString()).put("observations",o.text.toString()).put("date",now()).put("status","Solicitada");val l=data("requests");l.add(r);save("requests",l);requests()};button("Cancelar"){requests()}}
 private fun samples(){page("Amostras");button("+ Registrar amostra"){sampleForm()};val l=data("samples");if(l.isEmpty())label("Nenhuma amostra.");l.forEach{s->label("${s.optString("code")} • ${s.optString("patientName")}\n${s.optString("material")} • ${s.optString("status")}");button("Avançar etapa"){val st=listOf("Coletada","Recebida","Em processamento","Resultado","Liberada");s.put("status",st[(st.indexOf(s.optString("status"))+1).coerceAtMost(4)]);save("samples",l);samples()}};button("← Voltar"){home()}}
 private fun sampleForm(){val ps=data("patients");if(ps.isEmpty()){toast("Cadastre um paciente primeiro");return};page("Nova amostra");val sp=Spinner(this).apply{adapter=ArrayAdapter(this@MainActivity,android.R.layout.simple_spinner_dropdown_item,ps.map{it.optString("name")})};root.addView(sp);val c=field("Código da amostra");val m=field("Material");root.addView(c);root.addView(m);button("Salvar"){val p=ps[sp.selectedItemPosition];val s=JSONObject().put("id",id()).put("code",c.text.toString()).put("material",m.text.toString()).put("patientId",p.optString("id")).put("patientName",p.optString("name")).put("status","Coletada").put("date",now());val l=data("samples");l.add(s);save("samples",l);samples()};button("Cancelar"){samples()}}
 private fun stock(){page("Estoque e validade");button("+ Novo item"){stockForm()};val l=data("stock");if(l.isEmpty())label("Nenhum item.");l.forEach{s->label("${s.optString("name")} • Lote ${s.optString("lot")}\nValidade: ${s.optString("expiry")} • Qtde: ${s.optInt("qty")} • Mínimo: ${s.optInt("min")}");button("Dar baixa (-1)"){s.put("qty",(s.optInt("qty")-1).coerceAtLeast(0));save("stock",l);stock()}};button("← Voltar"){home()}}
 private fun stockForm(){page("Novo item");val n=field("Nome");val lot=field("Lote");val ex=field("Validade (MM/AAAA)");val q=field("Quantidade");val mn=field("Estoque mínimo");listOf(n,lot,ex,q,mn).forEach{root.addView(it)};button("Salvar"){val s=JSONObject().put("id",id()).put("name",n.text.toString()).put("lot",lot.text.toString()).put("expiry",ex.text.toString()).put("qty",q.text.toString().toIntOrNull()?:0).put("min",mn.text.toString().toIntOrNull()?:0);val l=data("stock");l.add(s);save("stock",l);stock()};button("Cancelar"){stock()}}
 private fun reports(){page("Resultados e relatórios");val r=data("requests");val s=data("samples");label("Pacientes: ${data("patients").size}\nSolicitações: ${r.size}\nAmostras: ${s.size}\nResultados liberados: ${r.count{it.optString("status")=="Liberada"}}\nAmostras liberadas: ${s.count{it.optString("status")=="Liberada"}}\nItens abaixo do mínimo: ${data("stock").count{it.optInt("qty")<=it.optInt("min")}}");button("← Voltar"){home()}}
 private fun appointments(){page("Agendamentos");button("+ Novo agendamento"){appointmentForm()};val l=data("appointments");if(l.isEmpty())label("Nenhum agendamento.");l.forEach{a->label("${a.optString("patientName")} • ${a.optString("date")}\n${a.optString("type")} • ${a.optString("status")}");button("Cancelar"){a.put("status","Cancelado");save("appointments",l);appointments()}};button("← Voltar"){home()}}
 private fun appointmentForm(){val ps=data("patients");if(ps.isEmpty()){toast("Cadastre um paciente primeiro");return};page("Novo agendamento");val sp=Spinner(this).apply{adapter=ArrayAdapter(this@MainActivity,android.R.layout.simple_spinner_dropdown_item,ps.map{it.optString("name")})};root.addView(sp);val d=field("Data e hora");val type=Spinner(this).apply{adapter=ArrayAdapter(this@MainActivity,android.R.layout.simple_spinner_dropdown_item,listOf("Coleta","Retorno","Consulta"))};root.addView(d);root.addView(type);button("Salvar"){val p=ps[sp.selectedItemPosition];val a=JSONObject().put("id",id()).put("patientId",p.optString("id")).put("patientName",p.optString("name")).put("date",d.text.toString()).put("type",type.selectedItem.toString()).put("status","Agendado");val l=data("appointments");l.add(a);save("appointments",l);appointments()};button("Cancelar"){appointments()}}
 private fun consultations(){page("Consultas");button("+ Nova consulta"){consultationForm()};val l=data("consultations");if(l.isEmpty())label("Nenhuma consulta.");l.forEach{c->label("${c.optString("patientName")} • ${c.optString("date")}\n${c.optString("notes")}")};button("← Voltar"){home()}}
 private fun consultationForm(){val ps=data("patients");if(ps.isEmpty()){toast("Cadastre um paciente primeiro");return};page("Nova consulta");val sp=Spinner(this).apply{adapter=ArrayAdapter(this@MainActivity,android.R.layout.simple_spinner_dropdown_item,ps.map{it.optString("name")})};root.addView(sp);val n=field("Anotações");root.addView(n);button("Salvar"){val p=ps[sp.selectedItemPosition];val c=JSONObject().put("id",id()).put("patientId",p.optString("id")).put("patientName",p.optString("name")).put("date",now()).put("notes",n.text.toString());val l=data("consultations");l.add(c);save("consultations",l);consultations()};button("Cancelar"){consultations()}}
 private fun delete(k:String,i:String,done:()->Unit){AlertDialog.Builder(this).setTitle("Excluir registro?").setNegativeButton("Cancelar",null).setPositiveButton("Excluir"){_,_->val l=data(k);l.removeAll{it.optString("id")==i};save(k,l);done()}.show()}
 private fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_SHORT).show()
}
